### ISSUE TITLE
format=pickle returns empty data set

### ISSUE THREAD

**Issue by reyjrar** [go-graphite/carbonzipper#29]
Pointing graphite-web at carbonzipper via CLUSTER_SERVERS in local_settings.py
```
2017/01/26 20:53:06 request:  /metrics/find/?local=1&format=pickle&query=%2A
2017/01/26 20:53:06 querying servers= [http://10.20.14.4:8080 http://10.20.28.2:8080] uri= /metrics/find/?format=protobuf&local=1&query=%2A
```
Receiving an empty response and no debugging information.  If I manually query the carbonserver instances for format={pickle,protobuf,json} I get valid data.

If I change:

```
2017/01/26 20:53:06 request:  /metrics/find/?local=1&format=pickle&query=%2A
```
TO
```
2017/01/26 20:53:06 request:  /metrics/find/?local=1&format=json&query=%2A
```

I get data.

I just pulled the latest master and built using golang 1.7.4 from golang.org.

**Comment by dgryski** [comment]
Weird.  It should handle this case.  I'll investigate this tomorrow.

**Comment by dgryski** [comment]
When I query carbonzipper with `/metrics/find/?local=1&format=pickle&query=%2`, I do get data back.  Maybe look at the responses that are coming back from carbonserver via wireshark (or enable debug logging with `-d=2`).  However, any errors should be logged, and I don't see those in what your pasted above.

**Comment by reyjrar** [comment]
There's some issues with carbonserver and the new release of graphite-web.  The names of the keys in the data structures don't line up anymore.

Since carbonzipper is relaying that data upstream, it's also broken.  You can't use carbonzipper/server with the master branch of graphite-web as "CLUSTER_SERVERS" as it's not compatible.

Some examples
```
/metrics/find/?_dc=1485911693610&query=*&format=treejson&path=&node=GraphiteTree
```
Returns a key of "metric_path", graphite-web remote_storage.py expects "path"

get_result in remote_storage.py expects 'is_leaf' and carbonserver is returning 'leaf'

**Comment by reyjrar** [comment]
Testing with -d=2 now.

**Comment by reyjrar** [comment]
This is the only information I get in the logs for the graphite-web tree requests when setting the carbonapi server as the graphite-web cluster server:

```
2017/02/01 01:43:04 request:  /metrics/find/?format=protobuf&query=%2A
2017/02/01 01:43:04 querying servers= [http://10.20.14.4:8080 http://10.20.28.2:8080] uri= /metrics/find/?format=protobuf&query=%2A
```

**Comment by Civil** [comment]
Can you try with current master and with debug loglevel?

**Comment by reyjrar** [comment]
OK, will rebuild and test

**Comment by Civil** [comment]
Have you tried with 0.80+?

**Comment by Civil** [comment]
no response for almost a year, I will assume that it's fixed now. Please reopen if it's not.
