### ISSUE TITLE
Explain "carbonapi >= 0.5. Note: we are not sure if there is any point in running carbonzipper over carbonapi at this moment."

### ISSUE THREAD

**Issue by joltcan** [go-graphite/carbonzipper#44]
Does that mean that carbonzipper is not needed when you have carbonapi, or that you can leave out carbonapi?

**Comment by Civil** [comment]
All our stuff speaks the same protobuf. So you can in theory do something like:
Carbonapi -> carbonzipper -> carbonapi -> go-carbon.

The thing is that we are not sure if there is any cases where you should use carbonapi as a **backend** for Carbonzipper.

You can leave out Carbonzipper I'd you don't need multiple backends (at this moment)
You also can use only zipper, if you want to run Graphite-web over it.

**Comment by joltcan** [comment]
Thanks for the clarification!
