### ISSUE TITLE
carbonzipper 0.72 exit code -1

### ISSUE THREAD

**Issue by osmufe** [go-graphite/carbonzipper#48]
Hi,

I Have these picture of graphite plaform  : 
![screen shot 2017-08-28 at 12 25 56](https://user-images.githubusercontent.com/12072489/29769781-12d959b8-8bec-11e7-85a8-e6854b7f074d.png)

I use graphite-web version 1.0.2 , carbonapi version 0.8.0 and carbonzipper version 0.70 because with carbonzipper 0.72 fails.

When graphite-web send a query with wildcard the carbonzipper dead , only have these logs:

```
child process died with exit code -1
W0825 14:45:46.199808   894 logging.cpp:91] RAW: Received signal SIGTERM from process 10326 of user 0; exiting
```

Thanks

**Comment by Civil** [comment]
That logs looks like they are not coming from zipper (zipper have no c++ code).
So I have some questions:
1. You are using packages we've built or you are building it by yourself?
2. Can you enable logs to file with level=debug and post the resulting log?
3. If the log is empty - can you please start it by hand with logging to stdout (debug level) and post the output here?

Thanks

**Comment by osmufe** [comment]
Hi,

Sorry for the delay and do not answer the questions.

I discovered an issue with own platform configuration that it causes the issue with docker log output ```child process died with exit code -1```
