### ISSUE TITLE
Make hostname configurable

### ISSUE THREAD

**Issue by ctrlok** [go-graphite/carbonzipper#50]
Hi. 

If you run carbonzipper in docker container you will have a lot of interesting hostnames. 

Maybe we can use a template for metrics? like go-carbon? 

```
graph-prefix = "carbon.agents.{host}"
```

**Comment by Civil** [comment]
https://github.com/go-graphite/carbonzipper/commit/2fac22996a68150be17a60d364402dabc99a2c1d
