### ISSUE TITLE
investigate if it's possible to remove stopTime from responses

### ISSUE THREAD

**Issue by Civil** [go-graphite/carbonzipper#58]
It seems that it's very easy to reconstruct stopTime out of data we receive. Is there any real need in having that in protocol?

**Comment by Civil** [comment]
@dgryski do you have any opinion about that? Maybe you remember the original reasoning behind having that in a first place?

**Comment by dgryski** [comment]
The original reasoning was probably due the protobuf to match the pickle, which had that field. If you remove it remember you're going to need an upgrade path: first set consumers to always calculate it, then afterwards set the servers to stop sending it.

**Comment by Civil** [comment]
I think it's not worth to remove it.
